USE [DFNB3];
GO

/****** Object:  Table [dbo].[tblRegionDim]    Script Date: 11/13/2019 5:27:00 PM ******/

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

CREATE TABLE dbo.tblRegionDim
(region_id   INT NOT NULL
, region_desc VARCHAR(50) NULL
, CONSTRAINT PK_tblRegionDim PRIMARY KEY CLUSTERED(region_id ASC)
  WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY];
GO