USE [DFNB3];
GO

/****** Object:  Table [dbo].[tblProductDim]    Script Date: 11/13/2019 5:26:41 PM ******/

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

CREATE TABLE dbo.tblProductDim
(prod_id   SMALLINT NOT NULL
, prod_desc VARCHAR(50) NULL
, CONSTRAINT PK_tblProductDim PRIMARY KEY CLUSTERED(prod_id ASC)
  WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY];
GO